paste0("Start time: ", format(Sys.time(), "%Y-%m-%d %H:%M:%S %Z", sep = "\n"))
################################################################################
##       R PROGRAM: PSE_get_LLM-hetero_estimates.R
##
##         PROJECT: Evaluation of multiple-encounter population size estimators
##
##
##     DESCRIPTION: Extract and consolidate PSE estimates generated by
##                  PSE_estimate_LLM-hetero.R into a single dataframe and save
##                  as both rds and csv.
##
##           INPUT: LLM_estimates-hetero.Rdata
##
##          OUTPUT: PSE_LLM-hetero_estimates.rds
##                  PSE_LLM-hetero_estimates.csv
##
##      WRITTEN BY: Steve Gutreuter, CDC/CGH/DGHT Statistics, Estimation
##                                   and Modeling Team
##                  sgutreuter@cdc.gov
##
##            DATE: 2020-07-14
##
################################################################################
library(tidyverse)
library(data.table)
basepath <- file.path(Sys.getenv("PROJ"), "PSE/PSEsim")
workpath <- file.path(basepath, "R")
datapath <- file.path(basepath, "data")
outpath <- file.path(basepath, "output")
setwd(workpath)
source(file.path(workpath, "PSE_sim_functions.R"))

est.objs <- "LLM_estimates-hetero.Rdata"

combineRdata <- function(Rdatanames, datapath){
    combined <- data.frame(NULL)
    counts <- data.frame(NULL)
    for(i in seq_along(Rdatanames)){
        efname <- file.path(datapath, Rdatanames[i])
        attach(efname, name = "currdata" )
        dfnames <- cgwtools::lsdata(efname)
        for(j in seq_along(dfnames)){
            dfj <- get(dfnames[j])
            if(substring(dfnames[j], 1, 3) == "llm"){

                dfj <- dfj[c("Events", "Repl","Ntrue", "Model", "Hetero", "Nest",
                             "Icoverage", "CIwidth", "lcl",  "ucl",
                             "gen.modl", "gen.parms")]
            }
            combined <- rbind(combined, dfj)
            x <- data.frame(with(dfj, table(Events)))
            counts <- rbind(counts,
                            cbind(rep(dfnames[j], nrow(x)), x))
        }
        detach(currdata)
    }
    names(counts) <- c("Estimates frame", "Events", "Estimates")
    invisible(list(combined = combined, counts = counts))
}

################################################################################
## Combine all estimates
################################################################################
comb.list <- combineRdata(est.objs, datapath = datapath)
comb <- comb.list$combined

################################################################################
## Recoding
################################################################################
## Code pmean = mean probability of detectection per observation event
Idx1 <- comb$gen.parms == "p = 0.025" |
    comb$gen.parms == "betaparms=(1.32448,51.6548)" |
    comb$gen.parms == "p0=0.025, frac=0.5" |
    comb$gen.parms == "betaparms=(1.32448,51.6548), frac=0.5"
Idx2 <- comb$gen.parms == "p = 0.05" |
    comb$gen.parms == "betaparms=(1.26488,24.0327)" |
    comb$gen.parms == "p0=0.05, frac=0.5" |
    comb$gen.parms == "betaparms=(1.26488,24.0327), frac=0.5"
Idx3 <- comb$gen.parms == "p = 0.1" |
    comb$gen.parms == "betaparms=(1.14567,10.3111)" |
    comb$gen.parms == "p0=0.1, frac=0.5" |
    comb$gen.parms == "betaparms=(1.14567,10.3111), frac=0.5"
Idx4 <- comb$gen.parms == "p = 0.15" |
    comb$gen.parms == "betaparms=(1.02647,5.81667)" |
    comb$gen.parms == "p0=0.15, frac=0.5" |
    comb$gen.parms == "betaparms=(1.02647,5.81667), frac=0.5"
comb$pmean[Idx1] <- "0.025"
comb$pmean[Idx2] <- "0.050"
comb$pmean[Idx3] <- "0.100"
comb$pmean[Idx4] <- "0.150"
## Identify SE estimation failures and correct Icoverage
comb$ISEfail <- ifelse(comb$CIwidth < 1, 1, 0)
comb$Icoverage <- ifelse(comb$ISEfail == 1, 0, comb$Icoverage)
## Correct Model name Mth to Mht
comb$Model[comb$Model == "Mth"] <- "Mht"            ## Fix Model name Mht
## Code an indicator of estimation failure (Nest <= 0)
comb$Ifail <- ifelse((comb$Nest <= 0 | is.na(comb$Nest)), 1, 0)

################################################################################
## Frequencies by data-generating model
################################################################################
table(comb$gen.modl)

################################################################################
## Frequencies by data-generating model and generating parameters
################################################################################
table(comb$gen.modl, comb$gen.parms)

################################################################################
## Save the data
################################################################################
comb$Model <- as.character(comb$Model)
comb$gen.modl <- as.character(comb$gen.modl)
comb$gen.parms <- as.character(comb$gen.parms)
saveRDS(comb, file = file.path(datapath, "PSE_LLM-hetero_estimates.rds"))
fwrite(comb, file = file.path(datapath, "PSE_LLM-hetero_estimates.csv"))
fwrite(comb.list$counts,
       file = file.path(outpath, "LLM-hetero_estimate_counts.csv"))
################################   END of FILE   ###############################
